// <auto-generated />
namespace BarEventsManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Readdedtables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Readdedtables));
        
        string IMigrationMetadata.Id
        {
            get { return "201705022159325_Readdedtables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
